spring.application.name=clab-backend
server.port=8080
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/CLAB
spring.datasource.username=postgres
spring.datasource.password=2006

spring.mvc.pathmatch.matching-strategy=ant_path_matcher


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=clmzclab@gmail.com
spring.mail.password=syhpcjstyaziwsjx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.proc.param_null_passing=true


jwt.secret=cLaB2026$eCuRiTyK3y#sYsTeM@LaBoRaToRiOs!uNiVeRsIdAd
